name: Deploy Pages (docs)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic sanity (files exist)
        run: |
          test -f SPEC.md
          test -f registry/issuers.json
          test -f test-vectors/valid_ar.json
          test -f docs/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
